### ISSUE TITLE
version 5.0.0 not working with jest

### ISSUE THREAD

**Issue by daniloab** [sindresorhus/convert-hrtime#6]
im using convert-hrtime and when tryting to run with jest using the version 5 does not work.

Then, I rollback to the version 3 and works normally

```
Details:

    /Users/daniloassis/Documents/projects/dab/myapp/node_modules/convert-hrtime/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export default function convertHrtime(hrtime) {
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'
```

**Comment by sindresorhus** [comment]
It's the other way around. It's Jest not working with this package because Jest does not fully support ESM. Open an issue on Jest instead.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
